### PR TITLE
feat: update browserslist version

### PR DESCRIPTION
**Pull request by yukipastelcat**
# Pull request summary

Related to [AUT-2510](https://oat-sa.atlassian.net/browse/AUT-2510).

Updated @oat-sa/browserslist-config-tao version to 1.0.0 in order to include removal of IE support

# How to test

1. Run it locally and see if IE is not present

# Checklist

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

### CODE REVIEW

**Review by oatymart — COMMENTED** [review]
It looks ok. The API is updated with correct versions when the build is run. Should the file `public/api.json` be updated and committed too? I get that it only really matters in the `gh-pages` branch build, but if this file is in the repo we might as well update it when we have a PR open.

**Comment by yukipastelcat** [comment]
@oatymart list is updated automatically when building, I've updated `@oat-sa/browserslist-config-tao` to 1.0.1 and built it, so now everything should be good

**Review by btamas — APPROVED** [review]
It works.

Screen Shot 2022-07-21 at 15 41 18

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — APPROVED** [review]
It works well.
IE removed as expected.

image

**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable) -- tests fails on the main branch already. Actually, the project does not contain tests.
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] ~~New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] ~~Pull request's target is not `master`~~ There is no `develop` branch...
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Pull request merged**
